# Generated by Django 3.1.4 on 2021-01-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wonder',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='wonder',
            name='title',
        ),
        migrations.RemoveField(
            model_name='wonder',
            name='year',
        ),
        migrations.AddField(
            model_name='wonder',
            name='store_name',
            field=models.CharField(max_length=100, null=True, verbose_name='식당 이름'),
        ),
        migrations.AddField(
            model_name='wonder',
            name='store_place',
            field=models.CharField(max_length=100, null=True, verbose_name='식당 위치'),
        ),
        migrations.AlterField(
            model_name='wonder',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
